### PR TITLE
bugfix #14

### LINKED ISSUE #14: Empty component-descriptor will not be overwtitten
**What happened**:
When trying to add to an existing empty component-descriptr, e.g.
`component-cli component-archive sources add test/component-archive --archive "test-archive" --component-name "example.com/component/name" --component-version "v0.0.1"`
an error comes up
`unable to parse component archive from test/component-archive: unable to parse component descriptor read from component-descriptor.yaml: component.name: Does not match pattern '^[a-z0-9.\-]+[.][a-z]{2,4}/[-a-z0-9/_.]*$';component.version: Does not match pattern '^[v]?(0|[1-9]\d*)(?:\.(0|[1-9]\d*))?(?:\.(0|[1-9]\d*))?(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'`

existing file was:
```
cat test/component-archive/component-descriptor.yaml 
component:
  componentReferences: []
  name: ""
  provider: internal
  repositoryContexts: []
  resources: []
  sources: []
  version: ""
meta:
  schemaVersion: v2
```

**What you expected to happen**:
document-descriptor should be overwritten
**How to reproduce it (as minimally and precisely as possible)**:
create fiel mentioned above and run command
**Anything else we need to know**:

**Environment**:

### PR DESCRIPTION
**Pull request by jschicktanz**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #14

**Special notes for your reviewer**:

**Release note**:

```bugfix user
Allows overwriting component name and version for empty component descriptors (issue #14) 
```

### CODE REVIEW

File: pkg/componentarchive/archive.go [hunk 1]
```diff
@@ -89,10 +91,35 @@ func (o *BuilderOptions) Build(fs vfs.FileSystem) (*ctf.ComponentArchive, error)
 			if err != nil {
 				return nil, fmt.Errorf("unable to create projectionfilesystem: %w", err)
 			}
-			archive, err := ctf.NewComponentArchiveFromFilesystem(archiveFs)
+
+			decodeOpts := []codec.DecodeOption{
+				codec.DisableValidation(true),
+			}
+			archive, err := ctf.NewComponentArchiveFromFilesystem(archiveFs, decodeOpts...)
```
Comment (schrodit) [inline pkg/componentarchive/archive.go:98]:
```suggestion
			archive, err := ctf.NewComponentArchiveFromFilesystem(archiveFs, codec.DisableValidation(true))
```

File: pkg/componentarchive/archive.go [hunk 2]
```diff
@@ -89,10 +91,35 @@ func (o *BuilderOptions) Build(fs vfs.FileSystem) (*ctf.ComponentArchive, error)
...
 			if err != nil {
 				return nil, fmt.Errorf("unable to parse component archive from %s: %w", o.ComponentArchivePath, err)
 			}
+
+			cd := archive.ComponentDescriptor
+
+			if o.Name != "" {
+				if cd.Name != "" && cd.Name != o.Name {
```
Comment (schrodit) [inline pkg/componentarchive/archive.go:106]:
```suggestion
				if cd.Name != o.Name {
```

File: pkg/componentarchive/archive.go [hunk 3]
```diff
@@ -89,10 +91,35 @@ func (o *BuilderOptions) Build(fs vfs.FileSystem) (*ctf.ComponentArchive, error)
...
+					return nil, fmt.Errorf("unable to overwrite the existing component name: forbidden")
+				}
+				cd.Name = o.Name
+			}
+
+			if o.Version != "" {
+				if cd.Version != "" && cd.Version != o.Version {
```
Comment (schrodit) [inline pkg/componentarchive/archive.go:113]:
```suggestion
				if cd.Version != o.Version {
```

File: pkg/componentarchive/archive.go [hunk 4]
```diff
@@ -89,10 +91,35 @@ func (o *BuilderOptions) Build(fs vfs.FileSystem) (*ctf.ComponentArchive, error)
...
+					return nil, fmt.Errorf("unable to overwrite the existing component version: forbidden")
```
Comment (schrodit) [inline pkg/componentarchive/archive.go:114]:
```suggestion
					return nil, errors.New("unable to overwrite the existing component version: forbidden")
```

File: pkg/componentarchive/archive.go [hunk 5]
```diff
@@ -89,10 +91,35 @@ func (o *BuilderOptions) Build(fs vfs.FileSystem) (*ctf.ComponentArchive, error)
...
+			archive, err := ctf.NewComponentArchiveFromFilesystem(archiveFs, decodeOpts...)
 			if err != nil {
 				return nil, fmt.Errorf("unable to parse component archive from %s: %w", o.ComponentArchivePath, err)
 			}
+
+			cd := archive.ComponentDescriptor
+
+			if o.Name != "" {
+				if cd.Name != "" && cd.Name != o.Name {
+					return nil, fmt.Errorf("unable to overwrite the existing component name: forbidden")
```
Comment (schrodit) [inline pkg/componentarchive/archive.go:107]:
```suggestion
					return nil, errors.New("unable to overwrite the existing component name: forbidden")
```

**Review by schrodit — CHANGES_REQUESTED** [review]

File: pkg/componentarchive/archive.go (hunk 2 above)
Comment (jschicktanz) [reply pkg/componentarchive/archive.go:106]: the suggested change doesn't work for cases where the existing cd name/version is empty and should be overwritten

Comment (schrodit) [reply pkg/componentarchive/archive.go:103]: hm but the statement `cd.Name != ""` is always true so you could also write `if true && cd.Name != o.Name {`.
Or am I missing something?

Comment (jschicktanz) [reply pkg/componentarchive/archive.go:103]: no cd.Name can be empty. I disabled the validation when loading the cd from the hard drive exactly for this case, which was the initial problem of the bug. and in case the name/version is empty, overwriting should be allowed.

Comment (schrodit) [reply pkg/componentarchive/archive.go:103]: ah yes you're sorry, miss-read the line above👍🏻

Comment (schrodit) [reply pkg/componentarchive/archive.go:103]: then everything is fine

**Review by schrodit — APPROVED** [review]
/lgtm

**Comment by schrodit** [comment]
@jschicktanz can also add a bugfix release note?

**Review by enrico-kaack-comp — APPROVED** [review]
